const ADD_WORKOUT = "ADD_WORKOUT";
const SET_GOALS = "SET_GOALS";
const WORKOUT_FILTER = "WORKOUT_FILTER";
const UPDATE_PROGRESS = "UPDATE_PROGRESS";

export { ADD_WORKOUT, SET_GOALS, WORKOUT_FILTER, UPDATE_PROGRESS };
